---
title: "Exploratory Plots"
author: "Matthew LH. Cheng"
date: "10/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load in packages
library(here)
library(tidyverse)
library(lubridate)

#set up working directory
getwd()

dir.data <- here("Data") #filepath to data

dir.fig<- here("Figures") #filepath to figures

#load in data for copmlete data set
#these data include smolt density data, total reactions, area of didson, bull 
#trout counts, day night cylce

# full dataset ------------------------------------------------------------
data <- read_csv(file = file.path(dir.data, "DIDSON_CompleteData.csv"))

```


This markdown document details exploratory plots for DIDSON Bull Trout counts.


```{r setting up data, echo = FALSE}
#setup dates/times
data<-data %>% 
  dplyr::rename(upstream = Upstream,
         downstream = Downstream,
         milling = Milling,
         total = Total,
         area = Area) %>% 
    mutate(date=str_sub(fixdate,1,16)) %>% 
  dplyr::select(-fixdate)
  
data$date<-force_tz(ymd_hm(data$date),"America/New_York") #forcing to EDT time zone


#selecting count data and standardizing to area
stand_count<-data %>% 
  mutate(standupstream = upstream/area, 
         standdownstream = downstream/area, 
         standmilling = milling/area,
         standtotalrxns = totalrxns/area) %>% 
  dplyr::select(standupstream, standdownstream, 
                standmilling, site, date)

#pivot standardized data long to wide to plot
stand_count_L<-stand_count %>% 
  pivot_longer(!date & !site , names_to = 'direction', values_to = 'count')
#does not equal data and site - don't pivot these
```

```{r FirstNight 2021 - Standrxns vs standcounts, echo = FALSE, fig.cap = "Standardized counts and standardized reactions across time at site FirstNight 2021 (Fence site)"}
data %>% 
  filter(site == 'firstnight2021') %>% 
  ggplot(.)+
  geom_line(aes(x = date, y = total/area, color = 'standcounts'),size = 1.5, alpha = 0.8)+  
  geom_line(aes(x=date, y=totalrxns/area*30, color = 'standrxn'),size = 1.5, alpha = 0.8)+  
  scale_y_continuous(name = "standcounts", 
                     sec.axis = sec_axis(~./30, name = 'standrxns'))+
    scale_color_manual(name = "",
                       values = c("standcounts" = "dodgerblue", "standrxn" = "orange"))+
        annotate("rect", xmin = as.POSIXct("2016-04-20 20:30:00 EDT"),
                 xmax = as.POSIXct("2016-04-21 05:56:00 EDT"), 
                 ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'firstnight2021')+
  theme_bw()

```

```{r Proportion of Downstream, Upstream, and Milling fish at site Firstnight 2021, echo = FALSE, fig.cap = "Proportion of Downstream, Upstream, and Milling fish at site Firstnight 2021" }
stand_count_L %>% #using pivoted data so I can plot stacked bars
  filter(site == 'firstnight2021') %>% 
  ggplot(.,aes(x = date, y = count, fill = direction))+
geom_bar(stat = 'identity', position = 'stack')+
  annotate("rect", xmin = as.POSIXct("2016-04-20 20:30:00 EDT"), 
           xmax = as.POSIXct("2016-04-21 05:56:00 EDT"), 
           ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'firstnight2021')+
  theme_bw()

```

```{r Standrxns and standCoutns at downstream 2122, echo = FALSE, fig.cap = "Standardized counts and standardized reactions across time at site Downstream2122"}
data %>% 
  filter(site == 'downstreamriver2122') %>% 
  ggplot(.)+
  geom_line(aes(x = date, y = total/area, color = 'standcounts'),size = 1.5, alpha = 0.8)+  
  geom_line(aes(x=date, y=totalrxns/area*30, color = 'standrxn'),size = 1.5, alpha = 0.8)+  
  scale_y_continuous(name = "standcounts", 
                     sec.axis = sec_axis(~./30, name = 'standrxns'))+
    scale_color_manual(name = "",
                       values = c("standcounts" = "dodgerblue", "standrxn" = "orange"))+
        annotate("rect", xmin = as.POSIXct("2016-04-21 20:30:00 EDT"),
                 xmax = as.POSIXct("2016-04-22 05:56:00 EDT"), 
                 ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'downstreamriver2122')+
  theme_bw()
```

```{r Proportion of Downstream, Upstream, and Milling fish at site Downstream 2122, echo = FALSE, fig.cap = "Proportion of Downstream, Upstream, and Milling fish at site Downstream 2122" }
stand_count_L %>% 
  filter(site == 'downstreamriver2122') %>% 
  ggplot(.,aes(x = date, y = count, fill = direction))+
geom_bar(stat = 'identity', position = 'stack')+
  annotate("rect", xmin = as.POSIXct("2016-04-21 20:30:00 EDT"), 
           xmax = as.POSIXct("2016-04-22 05:56:00 EDT"), 
           ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'downstreamriver2122')+
  theme_bw()
```
```{r Standrxns and standCoutns at downstream fence 2324, echo = FALSE, fig.cap = "Standardized counts and standardized reactions across time at site DownstreamFence 2324"}
data %>% 
  filter(site == 'downstreamfence2324') %>% 
  ggplot(.)+
  geom_line(aes(x = date, y = total/area, color = 'standcounts'),size = 1.5, alpha = 0.8)+  
  geom_line(aes(x=date, y=totalrxns/area*15, color = 'standrxn'),size = 1.5, alpha = 0.8)+  
  scale_y_continuous(name = "standcounts", 
                     sec.axis = sec_axis(~./15, name = 'standrxns'))+
    scale_color_manual(name = "",
                       values = c("standcounts" = "dodgerblue", "standrxn" = "orange"))+
  annotate("rect", xmin =as.POSIXct("2016-04-23 20:30:00 EDT"), 
           xmax = as.POSIXct("2016-04-24 05:56:00 EDT"),
           ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'downstreamfence2324')+
  theme_bw()
```
```{r Proportion of Downstream, Upstream, and Milling fish at site Downstream Fence 2324, echo = FALSE, fig.cap = "Proportion of Downstream, Upstream, and Milling fish at site Downstream Fence 2324" }
stand_count_L %>% 
  filter(site == 'downstreamfence2324') %>% 
  ggplot(.,aes(x = date, y = count, fill = direction))+
geom_bar(stat = 'identity', position = 'stack')+
  annotate("rect", xmin =as.POSIXct("2016-04-23 20:30:00 EDT"), 
           xmax = as.POSIXct("2016-04-24 05:56:00 EDT"), 
           ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'downstreamfence2324')+
  theme_bw()
```

```{r Standrxns and standCoutns at Narrows 2526, echo = FALSE, fig.cap = "Standardized counts and standardized reactions across time at site Narrows 2526"}
data %>% 
  filter(site == 'narrows2526') %>% 
  ggplot(.)+
  geom_line(aes(x = date, y = total/area, color = 'standcounts'),size = 1.5, alpha = 0.8)+  
  geom_line(aes(x=date, y=totalrxns/area*15, color = 'standrxn'),size = 1.5, alpha = 0.8)+  
  scale_y_continuous(name = "standcounts", 
                     sec.axis = sec_axis(~./15, name = 'standrxns'))+
    scale_color_manual(name = "",
                       values = c("standcounts" = "dodgerblue", "standrxn" = "orange"))+
  annotate("rect", xmin =as.POSIXct("2016-04-25 20:30:00 EDT"), 
           xmax = as.POSIXct("2016-04-26 05:56:00 EDT"), 
           ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'narrows2526')+
  theme_bw()
```
```{r Proportion of Downstream, Upstream, and Milling fish at site Narrows 2526, echo = FALSE, fig.cap = "Proportion of Downstream, Upstream, and Milling fish at site Narrows 2526" }
stand_count_L %>% 
  filter(site == 'narrows2526') %>% 
  ggplot(.,aes(x = date, y = count, fill = direction))+
geom_bar(stat = 'identity', position = 'stack')+
  annotate("rect", xmin =as.POSIXct("2016-04-25 20:30:00 EDT"),
           xmax = as.POSIXct("2016-04-26 05:56:00 EDT"), 
           ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'narrows2526')+
  theme_bw()
```

```{r Standrxns and standCoutns at Upstream Fence 272829, echo = FALSE, fig.cap = "Standardized counts and standardized reactions across time at site Upstream Fence 272829"}
data %>% 
  filter(site == 'upstream272829') %>% 
  ggplot(.)+
  geom_line(aes(x = date, y = upstream/area, color = 'standcounts'),size = 1.5, alpha = 0.8)+  
  geom_line(aes(x=date, y=totalrxns/area*5, color = 'standrxn'),size = 1.5, alpha = 0.8)+  
  scale_y_continuous(name = "standcounts", 
                     sec.axis = sec_axis(~./5, name = 'standrxns'))+
    scale_color_manual(name = "",
                       values = c("standcounts" = "dodgerblue", "standrxn" = "orange"))+
  annotate("rect", xmin =as.POSIXct("2016-04-27 20:30:00 EDT"), 
           xmax = as.POSIXct("2016-04-28 05:56:00 EDT"),
           ymin= -Inf,  ymax = Inf, alpha = 0.25)+
    annotate("rect", xmin =as.POSIXct("2016-04-28 20:30:00 EDT"),
             xmax = as.POSIXct("2016-04-29 05:56:00 EDT"), 
             ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'upstream272829')+
  theme_bw()
```
```{r Proportion of Downstream, Upstream, and Milling fish at site Upstream Fence 272829, echo = FALSE, fig.cap = "Proportion of Downstream, Upstream, and Milling fish at site Upstream 272829" }
stand_count_L %>% 
  filter(site == 'upstream272829') %>% 
  ggplot(.,aes(x = date, y = count, fill = direction))+
geom_bar(stat = 'identity', position = 'stack')+
  annotate("rect", xmin =as.POSIXct("2016-04-27 20:30:00 EDT"), 
           xmax = as.POSIXct("2016-04-28 05:56:00 EDT"), 
           ymin= -Inf,  ymax = Inf, alpha = 0.25)+
    annotate("rect", xmin =as.POSIXct("2016-04-28 20:30:00 EDT"), 
             xmax = as.POSIXct("2016-04-29 05:56:00 EDT"), 
             ymin= -Inf,  ymax = Inf, alpha = 0.25)+
  labs(title = 'upstream272829')+
  theme_bw()


```
```{r Standrxns and standCoutns at Narrows 29, echo = FALSE, fig.cap = "Standardized counts and standardized reactions across time at site Narrows 29"}
data %>% 
  filter(site == 'narrows29') %>% 
  ggplot(.)+
  geom_line(aes(x = date, y = total/area, color = 'standcounts'),size = 1.5, alpha = 0.8)+  
  geom_line(aes(x=date, y=totalrxns/area*3, color = 'standrxn'),size = 1.5, alpha = 0.8)+  
  scale_y_continuous(name = "standcounts", 
                     sec.axis = sec_axis(~./3, name = 'standrxns'))+
    scale_color_manual(name = "",
                       values = c("standcounts" = "dodgerblue", "standrxn" = "orange"))+
  labs(title = 'narrows29')+
  theme_bw()
```
```{r Proportion of Downstream, Upstream, and Milling fish at site Narrows 29, echo = FALSE, fig.cap = "Proportion of Downstream, Upstream, and Milling fish at site Narrows 29" }
stand_count_L %>% 
  filter(site == 'narrows29') %>% 
  ggplot(.,aes(x = date, y = count, fill = direction))+
geom_bar(stat = 'identity', position = 'stack')+
  labs(title = 'narrows29')+
  theme_bw()
```



